import os,sys

# hexDump
def hexDump(filename,buffer_name,cols = 16) :
    out = []
    out.append("""unsigned char %s[] = {""" % (buffer_name,))
    data = open(filename,'rb').read()
    for n in xrange(0,len(data),cols):
      out.append(",".join([str(ord(v)) for v in data[n:n+cols]])+',')
    out.append("""};""")
    out.append("")
    return '\n'.join(out)

if __name__ == '__main__':
    f = open('bytecode.h','wb')
    f.write("/*This file is autogenerated by generate_bytecode.py*/\n\n")
    for mod in ['tokenize','parse','encode','py2bc']:
        cmd='python py2bc.py %s.py %s.tpc' % (mod,mod)
        print("Executing " + cmd)
        os.system(cmd)
        f.write(hexDump(mod+".tpc",'tp_'+mod)+"\n")
    f.close()


